### ISSUE TITLE
Merkle Tree Gen and Proof verification fails 

### ISSUE THREAD

**Issue by laurahetz** [dedis/apir-code#17]
Hi,
Looking at the Merkle tree construction, I noticed that honestly generated proofs fail regularly for "larger" data sets, e.g., with 10,000 records.
This issue can be replicated by extending the existing test case for the proofs (see [here](https://github.com/laurahetz/apir-code/blob/c6dd9cb159f3c183caf8cef47d06f20e8dadc58f/lib/merkle/proof_test.go#L37)).
In this test case, a new Merkle tree is built and a proof is generated and validated for each data record.

It seems that the issue is caused by collisions in the adler32 checksum (which is used to generate the Merkle tree and the proofs).
I added another test case for the tree generation that fails due to collisions (see [here](https://github.com/laurahetz/apir-code/blob/c6dd9cb159f3c183caf8cef47d06f20e8dadc58f/lib/merkle/merkletree_test.go#L39C1-L39C33)).
I guess the checksum is intended to generate a unique key for each record that allows a mapping from data record to Merkle tree node index. So, using a better/cryptographic hash function should solve this, but at the cost of higher runtime?

Can you confirm this issue and provide any solution to it?

Thanks.
Laura

**Comment by si-co** [comment]
Hi Laura,

Thank you for identifying the issue so precisely and for providing the additional tests. I've resolved the problem by using a 64-bit checksum, which should be sufficient for any reasonable data set. While another approach could involve modifying the Merkle tree implementation to eliminate the need for a checksum altogether, I believe the current solution is adequate.

This change does not impact runtime since it only affects the Merkle tree generation, a process that is executed by the servers (1) offline and (2) only when the database is modified.

I also incorporated your additional tests into the code to confirm that the changes effectively address the issue. 

Thank you again for your contribution!

Simone
